### ISSUE TITLE
Smart-Ledger Interface endpoints for FAM

### ISSUE THREAD

**Issue by tantialex** [sunfish-prj/Registry-Interface#3]
[RIissue.xlsx](https://github.com/sunfish-prj/Registry-Interface/files/1398096/RIissue.xlsx)

Attached is an excel document with the needed endpoints by FAM & SLAM. Priority 0 and 1 are needed for the Demo however the rest can be included at a later stage.

**Comment by rsindper** [comment]
thanks for providing this! However, it seems to me there is some redundance in these APIs. Actually they are all doing four similar things: store, get, delete and update but for different categories. Can I suggest to keep them more concise and provide a more general set of APIs? Also, it would be great if you could provide a swagger definition rather than excel file? cheers @tantialex @andreamargheri

**Comment by tantialex** [comment]
The reason for the given APIs is so the administrator can manage each category on the FAM administration dashboard.
IE: adding, deleting, viewing & editing services.
I'm not sure if the APIs can be more concise however I am open to other solutions.
Cheers @RunshanHu

**Comment by sunfish-prj** [comment]
@RunshanHu you are misleading the conversion: at the level of SLI (ex RI) the API must be component-friendly, hence all needed parameters must be provided. The RI will take care of boiling them down to 'put', 'get', etc. This corresponds to what has been done both with policy and data masking.

**Comment by rsindper** [comment]
@sunfish-prj @tantialex thanks for the explanation. Can you please define them in the swagger file and I will proceed with them asap.

**Comment by sunfish-prj** [comment]
We will do it together and then submit to @tantialex
